# Generated by Django 4.2.14 on 2024-08-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='grduation',
            new_name='graduation',
        ),
    ]
