# Generated by Django 4.2.14 on 2024-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_rename_grduation_resumeprofile_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
