# Generated by Django 4.2.14 on 2024-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_resumeprofile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='DOB',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='addinfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='companyname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='datefrom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='dateto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='jobposition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='martialstatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='skillproficiency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
