# Generated by Django 4.2.14 on 2024-08-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_resumeprofile_dob_resumeprofile_addinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='fullname',
            new_name='firstname',
        ),
    ]
