# Generated by Django 4.2.14 on 2024-08-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_rename_fullname_resumeprofile_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='addinfo',
            new_name='DegreeCertification',
        ),
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='resumeprofile',
            old_name='companyname',
            new_name='universityCollege',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='datefrom',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='dateto',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='hss',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='jobposition',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='martialstatus',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='skillproficiency',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='sslc',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='surname',
        ),
    ]
