# Generated by Django 4.2.14 on 2024-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_resumeprofile_coursetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='prjectimg',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
