# Generated by Django 4.2.14 on 2024-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_resumeprofile_prjectimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='prjectlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
