# Generated by Django 4.2.14 on 2024-08-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0009_resumeprofile_prjectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='aboutme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='objective',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
